project:
  type: website
  output-dir: docs

website:
  title: "StatSeer"
  back-to-top-navigation: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    fig-cap-location: top



