---
title: "Aledari Heavy Weapons Technical Analysis"
subtitle: "Or, should you use anything else other than Bright Lances in 10th ed?"
author: "The Stat Seer"
date: 2025-03-01
date-format: long
execute:
  echo: false
  warning: false
website:
  back-to-top-navigation: true

---


# Intro
Aeldari heavy weapons are a set of 5 weapons that have been part of many Aeldari (or Eldar way before) since 3rd edition. They've been part of some of the most iconic model kits of the faction.


## Weapons
War Walkers, Wraithlord, Falcons, Wave Serpents and Guardians Defenders all can choose one or more of the following weaponry:

{{< include 'ahw_table.html' >}}

## Heatmaps

## Individual Units

::: {.panel-tabset}

## Battle Sisters Squad
{{< include 'stats_BSS.html' echo=false >}}

## Sororitas Rhino
{{< include 'stats_SR.html' echo=false >}}

## Custodian Guard
{{< include 'stats_CG.html' echo=false >}}

## Onager Dunecrawler
{{< include 'stats_OD.html' echo=false >}}

## Skitarii Vanguard
{{< include 'stats_SV.html' echo=false >}}

## Guardian Defenders
{{< include 'stats_GD.html' echo=false >}}

## Leman Russ Battle Tank
{{< include 'stats_LRBT.html' echo=false >}}

## Rogal Dorn Battle Tank
{{< include 'stats_RDBT.html' echo=false >}}

## Chimera
{{< include 'stats_Ch.html' echo=false >}}

## Cadian Shock Troops
{{< include 'stats_CST.html' echo=false >}}

## Daemon Prince of Chaos
{{< include 'stats_DPoC.html' echo=false >}}

## Beasts of Nurgle
{{< include 'stats_BoN.html' echo=false >}}

## Knight Abominant
{{< include 'stats_KA.html' echo=false >}}

## Incubi
{{< include 'stats_In.html' echo=false >}}

## Raider
{{< include 'stats_Ra.html' echo=false >}}

## Acolyte Hybrids
{{< include 'stats_AH.html' echo=false >}}

## Nemesis Dreadknight
{{< include 'stats_ND.html' echo=false >}}

## Knight Castellan
{{< include 'stats_KC.html' echo=false >}}

## Hekaton Land Fortress
{{< include 'stats_HLF.html' echo=false >}}

## Hearthkyn Warriors
{{< include 'stats_HW.html' echo=false >}}

## Canoptek Wraiths
{{< include 'stats_CW.html' echo=false >}}

## Necron Warriors
{{< include 'stats_NW.html' echo=false >}}

## Trukk
{{< include 'stats_Tr.html' echo=false >}}

## Boyz
{{< include 'stats_Bo.html' echo=false >}}

## Terminator Squad
{{< include 'stats_TS.html' echo=false >}}

## Intercessor Squad
{{< include 'stats_IS.html' echo=false >}}

## Impulsor
{{< include 'stats_Im.html' echo=false >}}

## Crisis Sunforge Battlesuits
{{< include 'stats_CSB.html' echo=false >}}

## Strike Team
{{< include 'stats_ST.html' echo=false >}}

## Tyrannofex
{{< include 'stats_Ty.html' echo=false >}}

## Tyrant Guard
{{< include 'stats_TG.html' echo=false >}}

## Termagants
{{< include 'stats_Te.html' echo=false >}}

:::







